# Generated by Django 4.2.7 on 2024-05-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0003_rename_purpose_subarea_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_registration',
            name='abstract_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
